name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2.1.5
        with:
          path: |
            node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}-
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn
      - run: yarn lint --max-warnings=0
      - run: yarn run-prettier -c
      - run: yarn typecheck